/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    media: Media;
    posts: Post;
    pages: Page;
    tags: Tag;
    biographies: Biography;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    biographies: BiographiesSelect<false> | BiographiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * The display name of the tenant/organization
   */
  name: string;
  /**
   * URL-friendly identifier (e.g., "acme-corp")
   */
  slug: string;
  /**
   * Optional description of the tenant/organization
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * User roles determine access levels across the system
   */
  roles: ('super-admin' | 'admin' | 'user')[];
  /**
   * Tenants this user belongs to
   */
  tenants?: (number | Tenant)[] | null;
  /**
   * Currently active tenant for this user
   */
  selectedTenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Make this post visible to the public
   */
  isPublished?: boolean | null;
  /**
   * When this post should be published
   */
  publishedDate?: string | null;
  /**
   * The author of this post
   */
  author?: (number | null) | User;
  /**
   * Tags for categorization
   */
  tags?: (number | Tag)[] | null;
  title: string;
  /**
   * URL-friendly identifier (e.g., "my-first-post")
   */
  slug: string;
  postType: 'article' | 'video' | 'audio' | 'document' | 'external';
  /**
   * Short summary for previews and SEO
   */
  excerpt?: string | null;
  /**
   * Main content of the post
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  video?: {
    /**
     * YouTube, Vimeo, or direct video URL
     */
    url?: string | null;
    /**
     * Duration (e.g., "10:30")
     */
    duration?: string | null;
    /**
     * Or upload a video file directly
     */
    file?: (number | null) | Media;
  };
  audio?: {
    /**
     * Spotify, SoundCloud, or direct audio URL
     */
    url?: string | null;
    /**
     * Duration (e.g., "45:00")
     */
    duration?: string | null;
    /**
     * Or upload an audio file directly
     */
    file?: (number | null) | Media;
  };
  document?: {
    /**
     * Upload a document (PDF, DOCX, etc.)
     */
    file?: (number | null) | Media;
    /**
     * Allow users to download this document
     */
    downloadable?: boolean | null;
  };
  external?: {
    /**
     * External URL to link to
     */
    url: string;
    /**
     * Open link in a new browser tab
     */
    openInNewTab?: boolean | null;
  };
  /**
   * Large banner image
   */
  banner?: (number | null) | Media;
  /**
   * Thumbnail for listings
   */
  thumbnail?: (number | null) | Media;
  /**
   * Add custom metadata fields to this post
   */
  customFields?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Optional description for this tag
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  status?: ('draft' | 'published') | null;
  publishedDate?: string | null;
  /**
   * Parent page for nested navigation
   */
  parent?: (number | null) | Page;
  title: string;
  /**
   * URL path for this page (e.g., "about-us")
   */
  slug: string;
  /**
   * Build your page using content blocks
   */
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            backgroundImage?: (number | null) | Media;
            alignment?: ('left' | 'center' | 'right') | null;
            buttons?:
              | {
                  label: string;
                  link: string;
                  variant?: ('primary' | 'secondary' | 'outline') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('narrow' | 'normal' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            media: number | Media;
            caption?: string | null;
            size?: ('small' | 'normal' | 'large' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            images: {
              image: number | Media;
              caption?: string | null;
              id?: string | null;
            }[];
            layout?: ('grid' | 'masonry' | 'carousel') | null;
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            description?: string | null;
            buttons?:
              | {
                  label: string;
                  link: string;
                  variant?: ('primary' | 'secondary') | null;
                  id?: string | null;
                }[]
              | null;
            style?: ('default' | 'centered' | 'background') | null;
            /**
             * CSS color value (e.g., #f5f5f5, rgb(0,0,0))
             */
            backgroundColor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            embedType: 'video' | 'audio' | 'social' | 'html';
            /**
             * Paste the URL of the content to embed
             */
            url?: string | null;
            /**
             * Custom embed code
             */
            html?: string | null;
            aspectRatio?: ('16:9' | '4:3' | '1:1') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
        | {
            layout: '2-equal' | '3-equal' | '4-equal' | '1-2' | '2-1' | '1-3' | '3-1';
            columns?:
              | {
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            verticalAlign?: ('top' | 'center' | 'bottom') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'columns';
          }
        | {
            /**
             * Optional heading above the accordion
             */
            heading?: string | null;
            items: {
              title: string;
              content: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            /**
             * Allow multiple items to be open at once
             */
            allowMultiple?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'accordion';
          }
        | {
            style?: ('line' | 'dashed' | 'dotted' | 'space') | null;
            spacing?: ('small' | 'medium' | 'large') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
        | {
            quote: string;
            author?: string | null;
            /**
             * Author title or role
             */
            authorTitle?: string | null;
            authorImage?: (number | null) | Media;
            style?: ('default' | 'large' | 'background') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
      )[]
    | null;
  meta?: {
    /**
     * Custom title for search engines (defaults to page title)
     */
    title?: string | null;
    /**
     * Meta description for search engines
     */
    description?: string | null;
    /**
     * Social sharing image
     */
    image?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "biographies".
 */
export interface Biography {
  id: number;
  tenant?: (number | null) | Tenant;
  avatar?: (number | null) | Media;
  /**
   * Tags for categorization
   */
  tags?: (number | Tag)[] | null;
  name: string;
  surname?: string | null;
  /**
   * Job title or role
   */
  title?: string | null;
  /**
   * City, country, or region
   */
  location?: string | null;
  /**
   * Biography or about text
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Social media links
   */
  socials?:
    | {
        platform:
          | 'website'
          | 'email'
          | 'linkedin'
          | 'twitter'
          | 'facebook'
          | 'instagram'
          | 'youtube'
          | 'tiktok'
          | 'github'
          | 'dribbble'
          | 'behance'
          | 'other';
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'biographies';
        value: number | Biography;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  tenants?: T;
  selectedTenant?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  tenant?: T;
  isPublished?: T;
  publishedDate?: T;
  author?: T;
  tags?: T;
  title?: T;
  slug?: T;
  postType?: T;
  excerpt?: T;
  content?: T;
  video?:
    | T
    | {
        url?: T;
        duration?: T;
        file?: T;
      };
  audio?:
    | T
    | {
        url?: T;
        duration?: T;
        file?: T;
      };
  document?:
    | T
    | {
        file?: T;
        downloadable?: T;
      };
  external?:
    | T
    | {
        url?: T;
        openInNewTab?: T;
      };
  banner?: T;
  thumbnail?: T;
  customFields?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  status?: T;
  publishedDate?: T;
  parent?: T;
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              alignment?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    link?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              media?: T;
              caption?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              layout?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    link?: T;
                    variant?: T;
                    id?: T;
                  };
              style?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              embedType?: T;
              url?: T;
              html?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        columns?:
          | T
          | {
              layout?: T;
              columns?:
                | T
                | {
                    content?: T;
                    image?: T;
                    id?: T;
                  };
              verticalAlign?: T;
              id?: T;
              blockName?: T;
            };
        accordion?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    content?: T;
                    id?: T;
                  };
              allowMultiple?: T;
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              style?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              author?: T;
              authorTitle?: T;
              authorImage?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "biographies_select".
 */
export interface BiographiesSelect<T extends boolean = true> {
  tenant?: T;
  avatar?: T;
  tags?: T;
  name?: T;
  surname?: T;
  title?: T;
  location?: T;
  bio?: T;
  socials?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}